site_name: Drupal Commerce Documentation
repo_url: https://github.com/centarro/commerce-docs
nav:
  - Introduction :
      - index.md
      - Contributing: 'contribute.md'
  - Commerce 1.x :
      - commerce1/getting-started.md
      - Developer Guide:
        - Getting started: commerce1/developer-guide/getting-started.md
        - Core Architecture: commerce1/developer-guide/core-architecture.md
        - Utilizing core APIs: commerce1/developer-guide/utilizing-core-APIs.md
        - Code Recipes: commerce1/developer-guide/code-recipes.md
      - User Guide:
        - commerce1/user-guide/index.md
        - Installation: commerce1/user-guide/installation.md
        - Products: commerce1/user-guide/products.md
        - Pricing: commerce1/user-guide/pricing.md
        - Shopping cart: commerce1/user-guide/shopping-cart.md
        - Checkout process: commerce1/user-guide/checkout-process.md
        - Payments: commerce1/user-guide/payments.md
        - Managing orders: commerce1/user-guide/managing-orders.md
        - Customer profiles: commerce1/user-guide/customer-profiles.md
        - Shipping: commerce1/user-guide/shipping.md
        - Tax Configuration: commerce1/user-guide/tax-configuration.md
      - Commerce Kickstart 2:
        - commerce1/commerce-kickstart-2/index.md
        - Installing and upgrading: commerce1/commerce-kickstart-2/installing-and-upgrading.md
        - Demo store features: commerce1/commerce-kickstart-2/demo-store-features.md
        - Products: 
          - commerce1/commerce-kickstart-2/products/index.md
          - Adding a new product: commerce1/commerce-kickstart-2/products/adding-new-product.md
          - Adding a taxonomy field to a Product for Attributes: commerce1/commerce-kickstart-2/products/adding-taxonomy-field.md
          - Adding images to variations and dealing with image styles: commerce1/commerce-kickstart-2/products/adding-images.md
          - Choosing between Page or Variation: commerce1/commerce-kickstart-2/products/choosing-between-page-variation.md
          - Product Management Overview: commerce1/commerce-kickstart-2/products/product-management-overview.md
        - Orders overview: commerce1/commerce-kickstart-2/orders-overview.md
        - Checkout overview: commerce1/commerce-kickstart-2/checkout-overview.md
        - Currency overview: commerce1/commerce-kickstart-2/currency-overview.md
        - Taxes overview: commerce1/commerce-kickstart-2/taxes-overview.md
        - Shipping: commerce1/commerce-kickstart-2/shipping.md
        - Translating a Commerce Store: commerce1/commerce-kickstart-2/translating-store.md
  - Commerce 2.x :
      - commerce2/getting-started.md
      - Installation, Updating & Uninstalling: 'commerce2/installation.md'
      - Contribute: 'commerce2/contribute.md'
      - Developer Guide:
        - commerce2/developer-guide/index.md
        - Core:
          - commerce2/developer-guide/core/core.md
          - Conditions: 'commerce2/developer-guide/core/conditions.md'
          - Sending HTML emails: 'commerce2/developer-guide/core/html_emails.md'
          - Understanding resolvers: 'commerce2/developer-guide/core/understanding_resolvers.md'
        - Products:
          - Getting started: 'commerce2/developer-guide/products/getting-started.md'
          - Product Information Structure: 'commerce2/developer-guide/products/product-information-structure.md'
          - Product Architecture: 'commerce2/developer-guide/products/product-architecture.md'
          - Product Management: 'commerce2/developer-guide/products/product-management.md'
          - Displaying Products: 'commerce2/developer-guide/products/displaying-products.md'
          - Marketing Products: 'commerce2/developer-guide/products/marketing-products.md'
        - Cart:
          - Cart events: 'commerce2/developer-guide/cart/cart-events.md'
          - Customize cart: 'commerce2/developer-guide/cart/customize-cart.md'
        - Customers:
          - Getting started: 'commerce2/developer-guide/customers/getting-started.md'
          - Addresses: 'commerce2/developer-guide/customers/addresses.md'
          - Profiles: 'commerce2/developer-guide/customers/profiles.md'
          - Customer Accounts & Groups: 'commerce2/developer-guide/customers/customer-accounts-groups.md'  
        - Payments:
          - Getting started: 'commerce2/developer-guide/payments/getting-started.md'
          - Gateways: 'commerce2/developer-guide/payments/gateways.md'
          - Creating Payment Gateway: 'commerce2/developer-guide/payments/creating-payment-gateway.md'
          - Payments: 'commerce2/developer-guide/payments/payments.md'
          - Code Recipes: 'commerce2/developer-guide/payments/code-recipes.md'
        - Stores:
          - Getting started: 'commerce2/developer-guide/stores/getting-started.md'
          - Code Recipes: 'commerce2/developer-guide/stores/code-recipes.md'
        - Orders:
          - Getting started: 'commerce2/developer-guide/orders/getting-started.md' 
          - Workflows: 'commerce2/developer-guide/orders/workflows.md'
          - Code Recipes: 'commerce2/developer-guide/orders/code-recipes.md'
        - Checkout: 'commerce2/developer-guide/checkout/checkout.md'
        - Pricing:
          - Getting started: 'commerce2/developer-guide/pricing/getting-started.md' 
          - Prices: 'commerce2/developer-guide/pricing/prices.md'
          - Adjustments: 'commerce2/developer-guide/pricing/adjustments.md'
          - Currencies: 'commerce2/developer-guide/pricing/currencies.md'
        - Promotions:
          - Getting started: 'commerce2/developer-guide/promotions/getting-started.md' 
          - Offers: 'commerce2/developer-guide/promotions/offers.md'
        - Activity log:
          - Getting started: 'commerce2/developer-guide/activity-log/getting-started.md' 
          - Code Recipes: 'commerce2/developer-guide/activity-log/code-recipes.md'
        - Shipping: 'commerce2/developer-guide/shipping/getting-started.md'
        - Recurring:
          - Getting started: 'commerce2/developer-guide/recurring/getting-started.md' 
          - Subscriptions: 'commerce2/developer-guide/recurring/subscriptions.md'
        - Adapting from 1.x: 'commerce2/developer-guide/adapting-from-1x.md'
      - User Guide:
        - commerce2/user-guide/index.md
        - Setting up your store: 'commerce2/user-guide/setting-up-store.md'
        - Currencies: 'commerce2/user-guide/currencies.md'
        - Products: 'commerce2/user-guide/products.md'
        - Orders: 'commerce2/user-guide/orders.md'
        - Payments: 'commerce2/user-guide/payments.md'
        - Promotions: 'commerce2/user-guide/promotions.md'
        - Taxes: 'commerce2/user-guide/taxes.md'
        - Checkout: 'commerce2/user-guide/checkout.md'
        - Shipping: 'commerce2/user-guide/shipping.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  font:
    text: Roboto
    code: 'Roboto Mono'
  logo: assets/logo.svg
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://centarro.io
  social:
    - icon: fontawesome/brands/slack
      link: https://drupal.slack.com/archives/C1TLCCF9B
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/centarrohq
    - icon: fontawesome/brands/github
      link: https://github.com/centarro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/centarro/
copyright:
  Copyright &copy; 2022 <a href="https://centarro.io" target="_blank">Centarro</a>
plugins:
  - search
  - include_dir_to_nav
  - open-in-new-tab
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
