site_name: Drupal Commerce Documentation
repo_url: https://github.com/centarro/commerce-docs
nav:
  - Introduction :
      - index.md
      - Contributing: 'contribute.md'
  - Commerce 2.x :
      - commerce2/getting-started.md
      - Installation, Updating & Uninstalling: 'commerce2/installation.md'
      - Contribute: 'commerce2/contribute.md'
      - Developer Guide:
        - commerce2/developer-guide/index.md
        - Core: 'commerce2/developer-guide/core.md'
        - Products:
          - Getting started: commerce2/developer-guide/products/getting-started.md
          - Product Information Structure: 'commerce2/developer-guide/products/product-information-structure.md'
          - Product Architecture: 'commerce2/developer-guide/products/product-architecture.md'
      - User Guide:
        - commerce2/user-guide/index.md
        - Setting up your store: 'commerce2/user-guide/setting-up-store.md'
        - Currencies: 'commerce2/user-guide/currencies.md'
        - Products: 'commerce2/user-guide/products.md'
        - Orders: 'commerce2/user-guide/orders.md'
        - Payments: 'commerce2/user-guide/payments.md'
        - Promotions: 'commerce2/user-guide/promotions.md'
        - Taxes: 'commerce2/user-guide/taxes.md'
        - Checkout: 'commerce2/user-guide/checkout.md'
        - Shipping: 'commerce2/user-guide/shipping.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.tabs.link
  font:
    text: Roboto
    code: 'Roboto Mono'
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://drupal.slack.com/archives/C1TLCCF9B
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/centarrohq
    - icon: fontawesome/brands/github
      link: https://github.com/centarro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/centarro/
copyright:
  Copyright &copy; 2022 <a href="centarro.io" target="_blank">Centarro</a>
plugins:
  - search
  - include_dir_to_nav
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
